# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: me.shawna jean
email: hello@shawnajroberts.com
description: yelling at the void
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://me.shawnajean.tech" # the base hostname & protocol for your site
home: "http://shawnajean.tech"
paginate: 5
paginate_path: /:num
timezone: America/New_York
permalink: /:slug

site_heading: >
  me<span class="faded">.shawna jean</span>

collections:
  my_tags:
    output: true
    permalink: /tag/:name/

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - github-pages

sass:
  style: compressed
  sass_dir: _sass

# Scopes
defaults:
  -
    scope:
      path:   ""
      type:   "pages"
    values:
      layout: "page"
  -
    scope:
      path:   ""
      type:   "posts"
    values:
      layout: "post"
  -
    scope:
      path:   ""
      type: my_tags
    values:
      layout: blog_by_tag

exclude: [Gemfile, vendor] # For travis ci
